const COUNTRY_CURRENCY: Record<string, string> = {
  AE: "AED",
  AR: "ARS",
  AT: "EUR",
  AU: "AUD",
  BD: "BDT",
  BE: "EUR",
  BG: "BGN",
  BH: "BHD",
  BR: "BRL",
  CA: "CAD",
  CH: "CHF",
  CL: "CLP",
  CN: "CNY",
  CO: "COP",
  CZ: "CZK",
  DE: "EUR",
  DK: "DKK",
  EG: "EGP",
  ES: "EUR",
  FI: "EUR",
  FR: "EUR",
  GB: "GBP",
  GH: "GHS",
  HK: "HKD",
  HU: "HUF",
  ID: "IDR",
  IL: "ILS",
  IN: "INR",
  IT: "EUR",
  JP: "JPY",
  KE: "KES",
  KR: "KRW",
  KW: "KWD",
  MX: "MXN",
  MY: "MYR",
  NG: "NGN",
  NL: "EUR",
  NO: "NOK",
  NZ: "NZD",
  PH: "PHP",
  PK: "PKR",
  PL: "PLN",
  PT: "EUR",
  QA: "QAR",
  RO: "RON",
  SA: "SAR",
  SE: "SEK",
  SG: "SGD",
  TH: "THB",
  TR: "TRY",
  TW: "TWD",
  US: "USD",
  VN: "VND",
  ZA: "ZAR",
};

const COUNTRY_LOCALE: Record<string, string> = {
  AE: "en-AE",
  AR: "es-AR",
  AT: "de-AT",
  AU: "en-AU",
  BD: "en-BD",
  BE: "nl-BE",
  BG: "bg-BG",
  BH: "en-BH",
  BR: "pt-BR",
  CA: "en-CA",
  CH: "de-CH",
  CL: "es-CL",
  CN: "zh-CN",
  CO: "es-CO",
  CZ: "cs-CZ",
  DE: "de-DE",
  DK: "da-DK",
  EG: "ar-EG",
  ES: "es-ES",
  FI: "fi-FI",
  FR: "fr-FR",
  GB: "en-GB",
  GH: "en-GH",
  GR: "el-GR",
  HK: "en-HK",
  HU: "hu-HU",
  ID: "id-ID",
  IE: "en-IE",
  IL: "he-IL",
  IN: "en-IN",
  IT: "it-IT",
  JP: "ja-JP",
  KE: "en-KE",
  KR: "ko-KR",
  KW: "ar-KW",
  MX: "es-MX",
  MY: "ms-MY",
  NG: "en-NG",
  NL: "nl-NL",
  NO: "nb-NO",
  NZ: "en-NZ",
  PH: "en-PH",
  PK: "en-PK",
  PL: "pl-PL",
  PT: "pt-PT",
  QA: "en-QA",
  RO: "ro-RO",
  SA: "ar-SA",
  SE: "sv-SE",
  SG: "en-SG",
  TH: "th-TH",
  TR: "tr-TR",
  TW: "zh-TW",
  US: "en-US",
  VN: "vi-VN",
  ZA: "en-ZA",
};

export function currencyForCountry(country: string): string {
  return COUNTRY_CURRENCY[country.toUpperCase()] ?? "USD";
}

export function localeForCountry(country: string): string {
  return COUNTRY_LOCALE[country.toUpperCase()] ?? "en-US";
}
