/** Indexable marketing routes for sitemap generation. */
export const MARKETING_PAGES = [
  { path: "/", changeFrequency: "weekly" as const, priority: 1 },
  { path: "/features", changeFrequency: "monthly" as const, priority: 0.9 },
  { path: "/how-it-works", changeFrequency: "monthly" as const, priority: 0.85 },
  { path: "/pricing", changeFrequency: "monthly" as const, priority: 0.9 },
  { path: "/tools", changeFrequency: "weekly" as const, priority: 0.9 },
  {
    path: "/tools/linkedin-character-counter",
    changeFrequency: "monthly" as const,
    priority: 0.85,
  },
  {
    path: "/tools/linkedin-text-formatter",
    changeFrequency: "monthly" as const,
    priority: 0.85,
  },
  { path: "/guides", changeFrequency: "weekly" as const, priority: 0.85 },
  {
    path: "/authors/linkedinpost-ai-content-team",
    changeFrequency: "monthly" as const,
    priority: 0.55,
  },
  { path: "/faq", changeFrequency: "monthly" as const, priority: 0.75 },
  { path: "/about", changeFrequency: "monthly" as const, priority: 0.7 },
  { path: "/contact", changeFrequency: "monthly" as const, priority: 0.6 },
  { path: "/compare", changeFrequency: "monthly" as const, priority: 0.8 },
  { path: "/compare/taplio", changeFrequency: "monthly" as const, priority: 0.75 },
  { path: "/compare/buffer", changeFrequency: "monthly" as const, priority: 0.75 },
  { path: "/compare/authoredup", changeFrequency: "monthly" as const, priority: 0.75 },
  { path: "/alternatives", changeFrequency: "monthly" as const, priority: 0.8 },
  {
    path: "/alternatives/taplio",
    changeFrequency: "monthly" as const,
    priority: 0.75,
  },
  {
    path: "/alternatives/buffer",
    changeFrequency: "monthly" as const,
    priority: 0.75,
  },
  {
    path: "/alternatives/authoredup",
    changeFrequency: "monthly" as const,
    priority: 0.75,
  },
  { path: "/for-founders", changeFrequency: "monthly" as const, priority: 0.8 },
  { path: "/for-agencies", changeFrequency: "monthly" as const, priority: 0.8 },
  { path: "/privacy", changeFrequency: "yearly" as const, priority: 0.3 },
  { path: "/terms", changeFrequency: "yearly" as const, priority: 0.3 },
] as const;
